# Generated by Django 4.0.3 on 2022-03-23 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OfficeEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=30, verbose_name='модель')),
                ('Owner', models.CharField(max_length=50, verbose_name='владелец')),
                ('cabinet', models.IntegerField()),
                ('sticker', models.CharField(max_length=10, verbose_name='стикер')),
                ('item_number', models.CharField(max_length=30, verbose_name='стикер')),
                ('status', models.CharField(choices=[('in_work', 'В работе'), ('in_stock', 'На складе'), ('under_repair', 'В ремонте')], max_length=15)),
                ('equipe_type', models.CharField(choices=[('mfu', 'МФУ'), ('printer', 'Принтер'), ('scaner', 'Сканер'), ('plotter', 'Плоттер')], max_length=15)),
                ('cartrige', models.CharField(max_length=50, verbose_name='картриджи')),
                ('connection_interfaces', models.CharField(max_length=50, verbose_name='доступные интерфейсы')),
                ('mac_addres', models.CharField(max_length=50, verbose_name='MAC-адрес')),
                ('ip_address', models.CharField(max_length=50, verbose_name='ip-адрес')),
                ('net_name', models.CharField(max_length=50, verbose_name='сетевое имя')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
