# Generated by Django 4.0.5 on 2022-06-10 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='owner',
            old_name='name',
            new_name='fname',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='cabinet',
        ),
        migrations.AddField(
            model_name='owner',
            name='lname',
            field=models.CharField(default=1, max_length=50, verbose_name='фамилия'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='owner',
            name='mname',
            field=models.CharField(default=2, max_length=50, verbose_name='отчество'),
            preserve_default=False,
        ),
    ]
