# Generated by Django 4.0.5 on 2022-06-14 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TypeOfficeEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equip_type', models.CharField(choices=[('mfu', 'МФУ'), ('printer', 'Принтер'), ('scanner', 'Сканер'), ('plotter', 'Плоттер')], max_length=15, verbose_name='тип устройства')),
                ('model', models.CharField(max_length=30, verbose_name='модель')),
                ('cartridge', models.CharField(max_length=50, verbose_name='картриджи')),
                ('interfaces', models.CharField(choices=[('usb', 'USB'), ('ethernet', 'Ethernet'), ('wifi', 'wi-fi')], max_length=50, verbose_name='доступные интерфейсы')),
            ],
        ),
    ]
