# Generated by Django 4.0.3 on 2022-03-23 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='имя')),
                ('cabinet', models.CharField(max_length=50, verbose_name='кабинет')),
            ],
        ),
        migrations.RenameField(
            model_name='officeequipment',
            old_name='Owner',
            new_name='owner',
        ),
        migrations.AlterField(
            model_name='officeequipment',
            name='cabinet',
            field=models.IntegerField(verbose_name='кабинет'),
        ),
        migrations.AlterField(
            model_name='officeequipment',
            name='equipe_type',
            field=models.CharField(choices=[('mfu', 'МФУ'), ('printer', 'Принтер'), ('scaner', 'Сканер'), ('plotter', 'Плоттер')], max_length=15, verbose_name='тип устройства'),
        ),
        migrations.AlterField(
            model_name='officeequipment',
            name='ip_address',
            field=models.CharField(max_length=50, verbose_name='IP-адрес'),
        ),
        migrations.AlterField(
            model_name='officeequipment',
            name='item_number',
            field=models.CharField(max_length=30, verbose_name='инвентарный номер'),
        ),
        migrations.AlterField(
            model_name='officeequipment',
            name='status',
            field=models.CharField(choices=[('in_work', 'В работе'), ('in_stock', 'На складе'), ('under_repair', 'В ремонте')], max_length=15, verbose_name='статус'),
        ),
    ]
