# Generated by Django 4.0.3 on 2022-03-24 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('technics', '0002_owner_rename_owner_officeequipment_owner_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='officeequipment',
            old_name='cartrige',
            new_name='cartridge',
        ),
        migrations.RenameField(
            model_name='officeequipment',
            old_name='mac_addres',
            new_name='mac_address',
        ),
        migrations.AlterField(
            model_name='officeequipment',
            name='equipe_type',
            field=models.CharField(choices=[('mfu', 'МФУ'), ('printer', 'Принтер'), ('scanner', 'Сканер'), ('plotter', 'Плоттер')], max_length=15, verbose_name='тип устройства'),
        ),
        migrations.AlterField(
            model_name='officeequipment',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='technics.owner'),
        ),
    ]
