# Generated by Django 4.0.3 on 2022-03-24 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('technics', '0003_rename_cartrige_officeequipment_cartridge_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='officeequipment',
            name='cabinet',
        ),
        migrations.AlterField(
            model_name='officeequipment',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.owner'),
        ),
        migrations.DeleteModel(
            name='Owner',
        ),
    ]
