# Generated by Django 4.0.3 on 2022-03-28 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technics', '0005_alter_officeequipment_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeOfficeEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equip_type', models.CharField(choices=[('mfu', 'МФУ'), ('printer', 'Принтер'), ('scanner', 'Сканер'), ('plotter', 'Плоттер')], max_length=15, verbose_name='тип устройства')),
                ('model', models.CharField(max_length=30, verbose_name='модель')),
                ('cartridge', models.CharField(max_length=50, verbose_name='картриджи')),
                ('interfaces', models.CharField(max_length=50, verbose_name='доступные интерфейсы')),
            ],
        ),
        migrations.RemoveField(
            model_name='officeequipment',
            name='cartridge',
        ),
        migrations.RemoveField(
            model_name='officeequipment',
            name='connection_interfaces',
        ),
        migrations.RemoveField(
            model_name='officeequipment',
            name='equip_type',
        ),
    ]
