# Generated by Django 4.0.5 on 2022-06-16 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('extras', '0001_initial'),
        ('technics', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficeEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sticker', models.CharField(max_length=10, verbose_name='стикер')),
                ('item_number', models.CharField(max_length=30, verbose_name='инвентарный номер')),
                ('status', models.CharField(choices=[('in_work', 'В работе'), ('in_stock', 'На складе'), ('under_repair', 'В ремонте')], max_length=15, verbose_name='статус')),
                ('mac_address', models.CharField(max_length=60, verbose_name='MAC-адрес')),
                ('ip_address', models.IntegerField(verbose_name='IP-адрес')),
                ('nat_name', models.CharField(max_length=60, verbose_name='сетевое имя')),
                ('ceate_date', models.DateField(verbose_name='дата создания')),
                ('comments', models.TextField(max_length=250, verbose_name='комментарий')),
                ('cabinet', models.IntegerField(verbose_name='кабинет')),
                ('interface', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='extras.interface', verbose_name='интерфейс подключения')),
                ('model', models.ForeignKey(max_length=30, on_delete=django.db.models.deletion.DO_NOTHING, to='technics.typeofficeequipment', verbose_name='модель')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.owner')),
            ],
        ),
    ]
